import fs from 'fs';
import path from 'path';
import { format } from 'date-fns';
import { Appointment, ReportData, Config } from '../types';
import { createChildLogger } from '../utils/logger';

const logger = createChildLogger('report');

export class ReportGenerator {
  private config: Config;

  constructor(config: Config) {
    this.config = config;
  }

  generateReport(appointments: Appointment[]): ReportData {
    const now = new Date();
    const formattedDate = format(now, 'yyyy-MM-dd HH:mm:ss');

    logger.info(
      { total: appointments.length, missingEmd: appointments.length },
      'Generating report data'
    );

    return {
      generatedAt: formattedDate,
      totalAppointments: appointments.length,
      missingEmdCount: appointments.length,
      appointments: appointments,
    };
  }

  async saveMarkdownReport(report: ReportData): Promise<string> {
    const filename = `amd-report-${format(new Date(), 'yyyy-MM-dd')}.md`;
    const filepath = path.join(this.config.reportSaveDir, filename);

    this.ensureReportDir();

    const content = this.generateMarkdownContent(report);

    fs.writeFileSync(filepath, content, 'utf-8');
    logger.info({ filepath }, 'Markdown report saved');

    return filepath;
  }

  async saveHtmlReport(report: ReportData): Promise<string> {
    const filename = `amd-report-${format(new Date(), 'yyyy-MM-dd')}.html`;
    const filepath = path.join(this.config.reportSaveDir, filename);

    this.ensureReportDir();

    const content = this.generateHtmlContent(report);

    fs.writeFileSync(filepath, content, 'utf-8');
    logger.info({ filepath }, 'HTML report saved');

    return filepath;
  }

  generateMarkdownContent(report: ReportData): string {
    const lines: string[] = [];

    lines.push('# AMD Appointment ID Report');
    lines.push('');
    lines.push(`**Generated:** ${report.generatedAt}`);
    lines.push(`**Total Appointments Checked:** ${report.totalAppointments}`);
    lines.push(`**Missing AMD ID Count:** ${report.missingEmdCount}`);
    lines.push('');

    if (report.appointments.length === 0) {
      lines.push('## No Missing AMD IDs Found');
      lines.push('');
      lines.push('All appointments for today have valid AMD Appointment IDs.');
      return lines.join('\n');
    }

    lines.push('## Appointments with Missing AMD IDs');
    lines.push('');

    lines.push('| Patient Name | Appointment Time | Doctor Name | Appointment ID | AMD Appointment ID | Status |');
    lines.push('|--------------|-------------------|-------------|----------------|---------------------|--------|');

    for (const apt of report.appointments) {
      const amdDisplay = this.formatAmdValue(apt.amd_appointment_id);
      lines.push(
        `| ${apt.patientName} | ${apt.appointmentTime} | ${apt.doctorName} | ${apt.appointmentId} | ${amdDisplay} | ${apt.status} |`
      );
    }

    lines.push('');
    lines.push('---');
    lines.push('');
    lines.push('*This report was automatically generated by the Halo Automation Agent.*');

    return lines.join('\n');
  }

  generateHtmlContent(report: ReportData): string {
    const tableRows = report.appointments
      .map(
        (apt) => `
        <tr>
          <td>${this.escapeHtml(apt.patientName)}</td>
          <td>${this.escapeHtml(apt.appointmentTime)}</td>
          <td>${this.escapeHtml(apt.doctorName)}</td>
          <td>${this.escapeHtml(apt.appointmentId)}</td>
          <td class="missing">${this.formatAmdValue(apt.amd_appointment_id)}</td>
          <td>${this.escapeHtml(apt.status)}</td>
        </tr>
      `
      )
      .join('');

    const noDataMessage =
      report.appointments.length === 0
        ? '<div class="no-data">No missing AMD IDs found. All appointments have valid AMD Appointment IDs.</div>'
        : '';

    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AMD Appointment ID Report - ${format(new Date(), 'yyyy-MM-dd')}</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            background: #f5f5f5;
            padding: 20px;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            border-radius: 8px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
            overflow: hidden;
        }
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
        }
        .header h1 {
            font-size: 28px;
            margin-bottom: 10px;
        }
        .header p {
            opacity: 0.9;
            font-size: 14px;
        }
        .stats {
            display: flex;
            gap: 20px;
            margin-top: 20px;
        }
        .stat-box {
            background: rgba(255,255,255,0.2);
            padding: 15px 25px;
            border-radius: 8px;
            text-align: center;
        }
        .stat-box .value {
            font-size: 32px;
            font-weight: bold;
        }
        .stat-box .label {
            font-size: 12px;
            opacity: 0.9;
        }
        .content {
            padding: 30px;
        }
        .no-data {
            text-align: center;
            padding: 40px;
            color: #22c55e;
            font-size: 18px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 14px;
        }
        thead {
            background: #f8f9fa;
        }
        th {
            text-align: left;
            padding: 15px;
            font-weight: 600;
            color: #374151;
            border-bottom: 2px solid #e5e7eb;
        }
        td {
            padding: 15px;
            border-bottom: 1px solid #e5e7eb;
            color: #1f2937;
        }
        tr:hover {
            background: #f9fafb;
        }
        .missing {
            color: #ef4444;
            font-weight: 500;
        }
        .status-badge {
            display: inline-block;
            padding: 4px 12px;
            border-radius: 20px;
            font-size: 12px;
            font-weight: 500;
        }
        .status-Scheduled { background: #dbeafe; color: #1d4ed8; }
        .status-InProgress { background: #fef3c7; color: #d97706; }
        .status-Completed { background: #d1fae5; color: #059669; }
        .status-Cancelled { background: #fee2e2; color: #dc2626; }
        .status-NoShow { background: #f3f4f6; color: #6b7280; }
        .footer {
            text-align: center;
            padding: 20px;
            color: #9ca3af;
            font-size: 12px;
            border-top: 1px solid #e5e7eb;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>AMD Appointment ID Report</h1>
            <p>Daily automated report for Halo Telehealth</p>
            <div class="stats">
                <div class="stat-box">
                    <div class="value">${report.totalAppointments}</div>
                    <div class="label">Total Checked</div>
                </div>
                <div class="stat-box">
                    <div class="value">${report.missingEmdCount}</div>
                    <div class="label">Missing AMD IDs</div>
                </div>
                <div class="stat-box">
                    <div class="value">${report.generatedAt}</div>
                    <div class="label">Generated At</div>
                </div>
            </div>
        </div>
        <div class="content">
            ${noDataMessage}
            <table>
                <thead>
                    <tr>
                        <th>Patient Name</th>
                        <th>Appointment Time</th>
                        <th>Doctor Name</th>
                        <th>Appointment ID</th>
                        <th>AMD Appointment ID</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    ${tableRows}
                </tbody>
            </table>
        </div>
        <div class="footer">
            Generated by Halo Automation Agent
        </div>
    </div>
</body>
</html>`;
  }

  getReportForTelegram(report: ReportData): string {
    const lines: string[] = [];

    lines.push('📊 *AMD Appointment ID Report*');
    lines.push('');
    lines.push(`📅 *Generated:* ${report.generatedAt}`);
    lines.push(`📋 *Total Checked:* ${report.totalAppointments}`);
    lines.push(`⚠️ *Missing AMD ID:* ${report.missingEmdCount}`);
    lines.push('');

    if (report.appointments.length === 0) {
      lines.push('✅ All appointments have valid AMD IDs!');
      return lines.join('\n');
    }

    lines.push('⚠️ *Appointments with missing AMD IDs:*');
    lines.push('');

    for (const apt of report.appointments) {
      lines.push(
        `• ${apt.patientName} | ${apt.appointmentTime} | Dr. ${apt.doctorName} | Status: ${apt.status}`
      );
    }

    lines.push('');
    lines.push('📎 Full report saved locally');

    return lines.join('\n');
  }

  private ensureReportDir(): void {
    if (!fs.existsSync(this.config.reportSaveDir)) {
      fs.mkdirSync(this.config.reportSaveDir, { recursive: true });
      logger.info({ dir: this.config.reportSaveDir }, 'Report directory created');
    }
  }

  private formatAmdValue(value: string | null | undefined): string {
    if (!value || value === 'null' || value === 'undefined' || value === '-' || value === 'N/A') {
      return '❌ MISSING';
    }
    return value;
  }

  private escapeHtml(text: string): string {
    const htmlEscapes: Record<string, string> = {
      '&': '&amp;',
      '<': '&lt;',
      '>': '&gt;',
      '"': '&quot;',
      "'": '&#39;',
    };
    return text.replace(/[&<>"']/g, (char) => htmlEscapes[char] || char);
  }
}

export function createReportGenerator(config: Config): ReportGenerator {
  return new ReportGenerator(config);
}